name: Hannah Image
favicon: null
layout_spectrum: 0.5701638169120997
typography_spectrum: 0.13999692886136472
title: Hannah Image
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0707420117687434
  lightness: 0.4761467189528048
  saturation: 0.7380920860450715
  rhythmicContrast: 0.7654254334047437
purpose: []
