name: Hannah Image
favicon: null
layout_spectrum: 0.23871
typography_spectrum: 0.47916
title: Hannah Image
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#20396e'
    - '#c7cdda'
    - '#2e529e'
    - '#848b9a'
  brandStrength: 0.125
  lightness: 0.4761467189528048
  saturation: 0.7380920860450715
  rhythmicContrast: 0.7654254334047437
purpose: []
